### PR TITLE
[FIX] path to tsconfig files

### PR DESCRIPTION
**Pull request by infabo**

### CODE REVIEW

**Comment by infabo** [comment]
I sincerely apologize for this pull request. I made every effort to submit a merge request on your GitLab instance, yet unfortunately, my registration never received approval. Additionally, I did not receive an email for the forget-password functionality, which prompted me to create the pull request here on the GitHub mirror.

I deeply regret any inconvenience caused by this situation and apologize for any disruption it may have caused you.

**Comment by infabo** [comment]
Dear @spoonerWeb ,

I hope this message finds you well. I wanted to follow up on the pull request I submitted approximately three months ago. I understand that you may have a busy schedule, and I greatly appreciate the time and effort you dedicate to maintaining the project.

I sincerely apologize if my initial message caused any confusion or inconvenience. I'm eager to contribute to the project and would be grateful for any feedback or guidance you could provide regarding the pull request. If there are any specific steps I need to take or additional information required, please let me know, and I'll be happy to address it promptly.

I understand that maintaining an open-source project can be challenging, and I truly appreciate your efforts in ensuring the project's success. Thank you for your time, and I look forward to hearing from you soon.

Best regards,
infabo

**Review by mirkanglanz — APPROVED** [review]
I noticed the same problem, and this pull request would fix it.

**Comment by spoonerWeb** [comment]
Will fix this and release an update after my holidays till End of May. 👍 
Thanks for your MR!

**Comment by topfender** [comment]
Is this still open? I would love to see this fixed soon, please :)

**Comment by infabo** [comment]
Thorough code review takes time.

**Comment by spoonerWeb** [comment]
Sorry for the late response. This repo is just a mirror and the management runs on my GitLab git.spooner.io.

Just added your changes and released version 3.0.1.

Thanks @infabo for this fix!

**Pull request closed without merging**
